[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "http://35.180.125.36/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
